window.newsFeed = [
  {
    source: "Reuters via MarketScreener",
    date: "2026-05-04",
    displayDate: "May 4, 2026",
    category: "ai-general-news",
    companies: ["Anthropic", "Blackstone", "Goldman Sachs", "Hellman & Friedman", "General Atlantic", "OpenAI"],
    title: "Reuters: Anthropic Nears $1.5B Wall Street Joint Venture to Sell AI Into Private Equity",
    url: "https://uk.marketscreener.com/news/anthropic-nears-1-5-billion-ai-joint-venture-with-wall-street-firms-wsj-reports-ce7f58deda8af227",
    summary:
      "Reuters, citing The Wall Street Journal, reported that Anthropic is finalizing an approximately $1.5 billion joint venture with Blackstone, Goldman Sachs, Hellman & Friedman, General Atlantic, and other Wall Street firms to sell AI tools to private-equity-backed companies. For AI-assisted teams, the signal is that frontier labs are turning enterprise distribution into a strategic advantage, with Claude Code and workflow automation becoming part of broader operating-company rollouts rather than isolated developer subscriptions.",
  },
  {
    source: "Business Insider",
    date: "2026-05-03",
    displayDate: "May 3, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "Stripe", "Sam Altman"],
    title: "Altman Says GPT-5.5 Planned Parts of Its Own Launch Event and Asked for a Feedback Hub",
    url: "https://www.businessinsider.com/sam-altman-gpt-5-5-ai-planned-party-2026-5",
    summary:
      "Business Insider reported that Sam Altman asked GPT-5.5 to plan elements of its own launch event, and the model suggested a structured gathering with a centralized feedback hub for future versions such as GPT-5.6. For AI-assisted teams, the useful signal is less the party anecdote than the product pattern: frontier labs are using high-capability models to design workflows around themselves while emphasizing tighter feedback loops for fast model iteration.",
  },
  {
    source: "Business Insider",
    date: "2026-05-03",
    displayDate: "May 3, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "xAI", "Elon Musk", "Sam Altman"],
    title: "Altman Extends Public Olive Branch to Musk Ahead of GPT-5.5 Launch",
    url: "https://www.businessinsider.com/sam-altman-elon-musk-trial-rivalry-gpt-party-openai-2026-5",
    summary:
      "Business Insider reported that Sam Altman said Elon Musk would be welcome at OpenAI's GPT-5.5 launch party even as their courtroom fight over OpenAI's mission and commercialization continues. For AI-assisted engineering teams, the useful signal is that model launches, corporate governance, and founder disputes are now tightly linked because legal outcomes can affect OpenAI's structure, partnerships, and product roadmap.",
  },
  {
    source: "San Francisco Chronicle",
    date: "2026-05-03",
    displayDate: "May 3, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "xAI", "Elon Musk", "Sam Altman"],
    title: "Federal Court Opens Live Audio Access for Musk v. OpenAI Trial",
    url: "https://www.sfchronicle.com/tech/article/elon-musk-openai-trial-broadcast-22238183.php",
    summary:
      "The San Francisco Chronicle reported that the Northern District of California will provide a live public audio feed for the Elon Musk lawsuit against OpenAI, with testimony expected from people tied to OpenAI's founding and governance. The practical takeaway for AI tooling watchers is that the trial is becoming an unusually transparent record of how frontier labs, nonprofit missions, model access, and commercial incentives were negotiated.",
  },
  {
    source: "The Verge",
    date: "2026-05-02",
    displayDate: "May 2, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "Microsoft", "xAI", "Meta", "Nvidia", "Google DeepMind"],
    title: "The Verge Tracks Early Evidence in Musk v. Altman Trial",
    url: "https://www.theverge.com/ai-artificial-intelligence/920775/evidence-exhibits-elon-musk-sam-altman-openai-trial",
    summary:
      "The Verge cataloged early exhibits from Musk v. Altman, including founding emails, governance documents, Nvidia infrastructure support, debates over control, and later commercial ties involving Microsoft. For teams relying on OpenAI-powered coding tools, the story matters because the trial evidence could shape how investors, enterprises, and regulators interpret model access, lab governance, and the durability of OpenAI's platform commitments.",
  },
  {
    source: "The Verge",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "Anthropic"],
    title: "The Verge: OpenAI Plans Restricted GPT-5.5-Cyber Access for Critical Defenders",
    url: "https://www.theverge.com/ai-artificial-intelligence/921073/openai-sam-altman-new-cybersecurity-model-gpt-5-5-cyber",
    summary:
      "The Verge reported that OpenAI is preparing GPT-5.5-Cyber for a limited rollout to vetted critical cyber defenders rather than broad public release. The practical takeaway for engineering and security teams is that the strongest AI security capabilities are being separated from ordinary product access, with eligibility, trust controls, and deployment context becoming part of the model roadmap.",
  },
  {
    source: "The Wall Street Journal",
    date: "2026-05-02",
    displayDate: "May 2, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "Microsoft", "Google", "Anthropic", "Meta"],
    title: "WSJ Profiles OpenAI CFO Sarah Friar as IPO Timing and Compute Spending Come Under Scrutiny",
    url: "https://www.wsj.com/business/openai-sam-altman-ipo-sarah-friar-392c582b",
    summary:
      "The Wall Street Journal reported that OpenAI CFO Sarah Friar is pushing more financial discipline as the company weighs a potential IPO, with compute commitments, missed internal growth targets, Microsoft deal work, and competition from Google and Anthropic shaping the debate. For AI-assisted engineering teams, the practical signal is that model access, pricing, and enterprise roadmap stability are increasingly tied to the economics of massive infrastructure commitments.",
  },
  {
    source: "Reuters via Dawn",
    date: "2026-05-02",
    displayDate: "May 2, 2026",
    category: "ai-general-news",
    companies: ["Pentagon", "OpenAI", "Google", "Nvidia", "Microsoft", "Amazon", "AWS", "SpaceX", "Reflection AI", "Anthropic"],
    title: "Reuters: Pentagon Expands Classified AI Partnerships While Anthropic Remains Sidelined",
    url: "https://www.dawn.com/news/1996808",
    summary:
      "Reuters reported that the Pentagon's new agreements will bring SpaceX, OpenAI, Google, Nvidia, Reflection AI, Microsoft, and AWS into classified Impact Level 6 and 7 environments, while Anthropic remains excluded after its dispute with the Defense Department over military-use guardrails. For AI tooling watchers, the important takeaway is that government access to frontier systems is being shaped by contract language, classified deployment paths, and vendor willingness to accept broad operational-use terms.",
  },
  {
    source: "GitHub Changelog",
    date: "2026-05-01",
    displayDate: "May 1, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft", "OpenAI"],
    title: "GitHub Will Deprecate GPT-5.2 and GPT-5.2-Codex Across Copilot on June 1",
    url: "https://github.blog/changelog/2026-05-01-upcoming-deprecation-of-gpt-5-2-and-gpt-5-2-codex/",
    summary:
      "GitHub said GPT-5.2 and GPT-5.2-Codex will be removed from most Copilot experiences on June 1, 2026, with GPT-5.5 and GPT-5.3-Codex listed as the suggested replacements. For VS Code and Copilot users, the practical step is to update workflows, model policies, and any integration assumptions before the old models disappear from chat, inline edits, ask mode, agent mode, and completions.",
  },
  {
    source: "Business Insider",
    date: "2026-05-01",
    displayDate: "May 1, 2026",
    category: "ai-general-news",
    companies: ["Meta", "OpenAI", "Anthropic", "SpaceX", "xAI", "Cursor"],
    title: "Zuckerberg Says Many AI Agents Still Are Not Polished Enough for Mainstream Users",
    url: "https://www.businessinsider.com/mark-zuckerberg-ai-agents-mother-test-openclaw-2026-5",
    summary:
      "Business Insider reported that Mark Zuckerberg used Meta's first-quarter earnings call to argue that many current AI agents remain too hard for mainstream users because they still require terminal setup, local configuration, or developer-style workflows. The takeaway for AI-assisted teams is that agent capability alone is not enough; products that want broad adoption need reliable setup, clear interaction patterns, and less operational friction than today's developer-focused tools.",
  },
  {
    source: "The Guardian",
    date: "2026-05-01",
    displayDate: "May 1, 2026",
    category: "ai-general-news",
    companies: ["Pentagon", "OpenAI", "Google", "Nvidia", "Microsoft", "Amazon", "AWS", "SpaceX", "Reflection AI", "Anthropic"],
    title: "Pentagon Signs AI Agreements With OpenAI, Google, Microsoft, AWS, Nvidia, SpaceX, and Reflection AI",
    url: "https://www.theguardian.com/us-news/2026/may/01/pentagon-us-military-pairs-with-spacex-google-openai",
    summary:
      "The Guardian, with Reuters reporting, said the Pentagon reached agreements with seven major AI and infrastructure companies as part of a push to make the U.S. military an \"AI-first fighting force.\" For teams tracking AI tooling, the practical signal is that frontier models, cloud platforms, GPUs, and agent infrastructure are being pulled deeper into classified and high-assurance government environments, while Anthropic remains a notable exception because of its dispute with the Defense Department.",
  },
  {
    source: "Axios",
    date: "2026-05-01",
    displayDate: "May 1, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "White House", "Pentagon", "OpenAI", "Google"],
    title: "Axios: Washington Reconsiders Its Anthropic Standoff as Mythos Becomes Hard to Ignore",
    url: "https://www.axios.com/2026/05/01/washington-new-anthropic-problem",
    summary:
      "Axios reported that the White House is moving toward re-engaging with Anthropic after months of Pentagon disputes, lawsuits, and supply-chain-risk concerns because Anthropic's most advanced systems, including Mythos, are becoming too important for agencies to ignore. The takeaway for AI-assisted teams is that access to high-capability models is increasingly being negotiated through government contracts, risk designations, and deployment controls rather than simple product availability.",
  },
  {
    source: "Microsoft On the Issues",
    date: "2026-05-01",
    displayDate: "May 1, 2026",
    category: "ai-general-news",
    companies: ["Microsoft", "Anthropic", "Claude", "Mythos"],
    title: "Microsoft Calls for Guardrails Around Next-Generation AI Cyber Capabilities",
    url: "https://blogs.microsoft.com/on-the-issues/2026/05/01/from-capability-to-responsibility-securing-our-global-digital-ecosystem-with-next-generation-ai/",
    summary:
      "Microsoft warned that advanced AI models are sharply accelerating vulnerability discovery, pointing to Claude Mythos Preview as evidence that cybersecurity is entering a new phase. The practical takeaway for AI-assisted teams is that powerful coding and security agents need enterprise controls, trusted access paths, and coordinated disclosure practices so faster bug discovery improves defense instead of expanding the attack surface.",
  },
  {
    source: "GitHub Changelog",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft", "Visual Studio"],
    title: "GitHub Brings Copilot Cloud Agents and Debugger Agent Workflows Into Visual Studio",
    url: "https://github.blog/changelog/2026-04-30-github-copilot-in-visual-studio-april-update/",
    summary:
      "GitHub's April Copilot update for Visual Studio adds direct cloud-agent session launches from the IDE, user-level custom agent definitions, broader agent-skill discovery paths, and a debugger agent workflow that can reproduce, instrument, diagnose, and suggest fixes from GitHub or Azure DevOps issues. For VS Code and Copilot users, the broader signal is that agentic development is moving deeper into daily IDE workflows, with live runtime validation becoming part of the expected agent toolchain.",
  },
  {
    source: "The Verge",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "ai-general-news",
    companies: ["Microsoft", "OpenAI", "Amazon", "Anthropic", "Google"],
    title: "The Verge: Microsoft's OpenAI Deal Shifts From Exclusivity Toward Multi-Cloud Economics",
    url: "https://www.theverge.com/tech/921210/microsoft-openai-partnership-divorce-notepad",
    summary:
      "The Verge broke down Microsoft's revised OpenAI agreement, emphasizing that OpenAI can now offer products across other cloud providers while Microsoft keeps a financial stake in OpenAI revenue, first access on Azure, and model rights through 2032. The practical takeaway for AI-assisted teams is that enterprise model access is becoming less exclusive and more multi-cloud, while Microsoft increasingly positions its AI stack around orchestration across OpenAI, Anthropic, Google, and its own models.",
  },
  {
    source: "The Wall Street Journal",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "White House", "OpenAI", "Google"],
    title: "WSJ: White House Opposes Anthropic Plan to Broaden Mythos Access",
    url: "https://www.wsj.com/tech/ai/white-house-opposes-anthropics-plan-to-expand-access-to-mythos-model-dc281ab5",
    summary:
      "The Wall Street Journal reported that the White House opposed Anthropic's plan to expand Mythos access beyond a small group of critical-infrastructure users, citing national-security risk, cyber misuse concerns, and scarce compute capacity. For teams tracking frontier model governance, the practical signal is that highly capable cyber models are now being treated as controlled infrastructure whose rollout can be constrained by federal security priorities, not just vendor readiness.",
  },
  {
    source: "Business Insider",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "ai-general-news",
    companies: ["Anthropic"],
    title: "Business Insider: Anthropic Doubles Its Claude Code Token-Cost Estimates",
    url: "https://www.businessinsider.com/anthropic-claude-code-token-estimates-2026-4",
    summary:
      "Business Insider reported that Anthropic raised its estimated Claude Code usage cost for enterprise developers from about $6 to about $13 per active day, with 90% of users now expected to stay under about $30 per active day. The change is important for AI-assisted engineering teams because agentic coding budgets are becoming a planning item: more capable models and heavier workflows can change real usage economics even when list prices do not formally change.",
  },
  {
    source: "Axios",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "Anthropic", "Stanford"],
    title: "Axios Warns AI Capability Growth Is Outrunning Transparency and Oversight",
    url: "https://www.axios.com/2026/04/29/ai-models-speed-warning",
    summary:
      "Axios' Behind the Curtain column pulled together recent signals on AI's acceleration, including coding models being used to build more software, concerns about recursive self-improvement, and Stanford's finding that the most capable foundation models are becoming less transparent. For VS Code users, the useful takeaway is that productivity gains from agents are arriving alongside weaker public visibility into how frontier systems are trained, evaluated, and governed.",
  },
  {
    source: "The Verge",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["Oracle", "OpenAI", "Microsoft", "Google", "Meta"],
    title: "The Verge: Oracle's AI Infrastructure Pivot Ties Its Future to OpenAI Demand",
    url: "https://www.theverge.com/ai-artificial-intelligence/920378/oracle-openai-datacenter-buildout",
    summary:
      "The Verge examined Oracle's aggressive AI infrastructure turn, including its large OpenAI data-center commitments and the financial, energy, supply-chain, and execution risks attached to that strategy. The story matters for AI tooling teams because model availability, latency, and price increasingly depend on enormous infrastructure bets by cloud and database companies, not only on model research progress inside the labs.",
  },
  {
    source: "Axios",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "ai-general-news",
    companies: ["Amazon", "Anthropic", "Google", "Meta", "Microsoft", "OpenAI", "xAI"],
    title: "Axios: Senators Press Major AI Labs and Cloud Firms on China-Related Insider Safeguards",
    url: "https://www.axios.com/2026/04/29/ai-firms-china-congress",
    summary:
      "Axios reported that Sens. Chuck Grassley and Jim Banks sent identical letters to major AI and cloud companies asking how they vet privileged staff, monitor insider risk, and protect model weights and adjacent assets from access tied to the PRC. For teams building or buying AI tools, the practical signal is that frontier-model governance is shifting beyond external hacking toward workforce access controls, supply-chain trust, and auditability.",
  },
  {
    source: "Axios",
    date: "2026-04-30",
    displayDate: "April 30, 2026",
    category: "ai-general-news",
    companies: ["Anthropic", "Google", "OpenAI", "Amazon", "Microsoft"],
    title: "Axios: OpenAI, Anthropic, and Google Are Trading Places Faster Than Enterprise Buyers Can Plan",
    url: "https://www.axios.com/2026/04/30/openai-anthropic-winners-losers-ipo",
    summary:
      "Axios argued that the AI market has entered a rapid-rotation phase in which OpenAI, Anthropic, and Google can gain or lose momentum within a single quarter, pushing enterprise buyers to avoid long commitments to any one model provider. For VS Code and Copilot users, the relevant takeaway is that multi-model workflows and vendor flexibility are becoming strategic requirements rather than optional experimentation.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["Anthropic", "OpenAI"],
    title: "TechCrunch: Anthropic Could Raise Another $50B at Up to a $900B Valuation",
    url: "https://techcrunch.com/2026/04/29/sources-anthropic-could-raise-a-new-50b-round-at-a-valuation-of-900b/",
    summary:
      "TechCrunch reported that Anthropic is weighing a fresh $40 billion to $50 billion round that could value the company between roughly $850 billion and $900 billion, driven in part by surging demand for Claude Code and Cowork. The story matters because it shows how strongly investors now value AI coding distribution, and how much capital the biggest labs may keep absorbing to fund model development, enterprise sales, and compute.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["Microsoft", "OpenAI", "Anthropic"],
    title: "TechCrunch: Nadella Says Microsoft Plans to 'Exploit' Its Revised OpenAI Deal",
    url: "https://techcrunch.com/2026/04/29/satya-nadella-says-hes-ready-to-exploit-the-new-openai-deal/",
    summary:
      "TechCrunch reported that Satya Nadella framed Microsoft's amended OpenAI agreement as a direct advantage, emphasizing royalty-free access to frontier OpenAI IP through 2032 while also positioning Azure as a multi-model platform spanning OpenAI, Anthropic, and open source. For developers and engineering leaders, the takeaway is that major platforms are now competing less on exclusive model access and more on orchestration, distribution, and enterprise infrastructure.",
  },
  {
    source: "Anthropic",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "mythos-news",
    companies: ["Anthropic"],
    title: "Anthropic Updates Responsible Scaling Policy With Stronger External Review Rules",
    url: "https://www.anthropic.com/responsible-scaling-policy",
    summary:
      "Anthropic updated its Responsible Scaling Policy to version 3.2, authorizing its Long-Term Benefit Trust to request external reviews of risk reports, approve the choice of outside reviewers, and receive regular briefings. For teams tracking Mythos-class capability governance, the important signal is that Anthropic is adding more formal oversight around frontier-risk evaluation instead of treating model-safety review as an internal-only process.",
  },
  {
    source: "Axios",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "White House", "Pentagon", "OpenAI", "Google"],
    title: "Axios: White House Drafts Path to Restore Anthropic Access for U.S. Agencies",
    url: "https://www.axios.com/2026/04/29/trump-anthropic-pentagon-ai-executive-order-gov",
    summary:
      "Axios reported that the White House is developing guidance that could let agencies work around Anthropic's supply-chain risk designation and regain access to newer models including Mythos. The story matters because it suggests federal AI policy is shifting from a blacklist posture toward a model-access and governance posture, with Anthropic, OpenAI, and Google all being treated as strategic infrastructure vendors.",
  },
  {
    source: "Microsoft Source",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["Microsoft", "OpenAI", "Azure"],
    title: "Microsoft Says Its AI Business Reached a $37B Annual Revenue Run Rate",
    url: "https://news.microsoft.com/source/2026/04/29/microsoft-cloud-and-ai-strength-fuels-third-quarter-results/",
    summary:
      "Microsoft said its AI business surpassed a $37 billion annual revenue run rate, up 123% year over year, while Azure and other cloud services grew 40%. For Copilot and VS Code users, the practical takeaway is that AI-assisted development is now being funded and scaled as core cloud infrastructure, not as an experimental add-on business.",
  },
  {
    source: "OpenAI",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "OpenAI Publishes a Cybersecurity Action Plan for the 'Intelligence Age'",
    url: "https://openai.com/index/cybersecurity-in-the-intelligence-age/",
    summary:
      "OpenAI published a five-part action plan focused on democratizing cyber defense, coordinating with government, tightening controls around frontier cyber capabilities, preserving deployment visibility, and helping users protect themselves. For teams building or adopting AI tools, the practical signal is that model providers are increasingly treating cybersecurity as a deployment and governance problem, not just a safety-policy discussion.",
  },
  {
    source: "Axios",
    date: "2026-04-29",
    displayDate: "April 29, 2026",
    category: "ai-general-news",
    companies: ["Google", "OpenAI", "Anthropic", "Pentagon", "U.S. Congress"],
    title: "Axios: Congress Is Behind the Pentagon's Rapid AI Contracting Push",
    url: "https://www.axios.com/2026/04/29/congress-military-ai-google-pentagon-deal",
    summary:
      "Axios reported that Congress is still far from passing military AI guardrails while the Pentagon expands model access through new contracts, including Google's reportedly permissive agreement for classified settings. The story matters for AI tool watchers because it highlights a widening gap between private-sector frontier model deployment, national-security procurement, and enforceable policy around autonomous weapons, mass surveillance, and human oversight.",
  },
  {
    source: "About Amazon",
    date: "2026-04-28",
    displayDate: "April 28, 2026",
    category: "ai-general-news",
    companies: ["Amazon", "AWS", "OpenAI"],
    title: "AWS Adds OpenAI Models, Codex, and Managed Agents to Amazon Bedrock",
    url: "https://www.aboutamazon.com/news/aws/bedrock-openai-models",
    summary:
      "Amazon announced a broader AWS and OpenAI partnership that brings the latest OpenAI models, Codex on Amazon Bedrock, and Amazon Bedrock Managed Agents powered by OpenAI into limited preview. For VS Code and Copilot users, the important signal is that OpenAI's coding-agent workflows are becoming available through enterprise cloud controls such as IAM, PrivateLink, logging, encryption, procurement commitments, and existing AWS governance.",
  },
  {
    source: "Axios",
    date: "2026-04-28",
    displayDate: "April 28, 2026",
    category: "mythos-news",
    companies: ["OpenAI", "Anthropic", "U.S. House Homeland Security Committee"],
    title: "OpenAI and Anthropic Brief House Staff on Advanced Cyber Models",
    url: "https://www.axios.com/2026/04/28/openai-anthropic-congress-cyber-briefings",
    summary:
      "Axios reported that OpenAI and Anthropic gave classified briefings to House Homeland Security Committee staff about their newest cyber-capable models, including Anthropic's restricted Mythos Preview. The story matters because it shows frontier model oversight shifting from abstract hearings into concrete briefings about infrastructure risk, deployment controls, and how quickly Congress needs to catch up with model capabilities.",
  },
  {
    source: "Reuters",
    date: "2026-04-28",
    displayDate: "April 28, 2026",
    category: "ai-general-news",
    companies: ["Goldman Sachs", "Anthropic"],
    title: "Goldman Cuts Claude Access for Hong Kong Bankers Amid AI Risk Scrutiny",
    url: "https://wsau.com/2026/04/28/goldman-sachs-bars-hong-kong-bankers-from-anthropic-ai-use-ft-reports/",
    summary:
      "Reuters reported that Goldman Sachs removed access to Anthropic's Claude for bankers in Hong Kong while leaving other models such as Gemini and ChatGPT available on its internal platform. For enterprise AI users, the move is a useful reminder that model access is increasingly being shaped by jurisdiction, contract interpretation, and cyber-risk controls rather than by technical capability alone.",
  },
  {
    source: "GitHub Blog",
    date: "2026-04-28",
    displayDate: "April 28, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "GitHub Says Agentic Development Workflows Are Driving a Need for 30x More Scale",
    url: "https://github.blog/news-insights/company-news/an-update-on-github-availability/",
    summary:
      "GitHub's latest availability update says the platform started planning for a 10x capacity increase in late 2025, then had to design for 30x scale as agentic software workflows accelerated. That is a useful operating signal for VS Code and Copilot users: AI-assisted coding is no longer a side feature at platform scale, and reliability work is increasingly being driven by autonomous and high-volume development usage.",
  },
  {
    source: "The Verge",
    date: "2026-04-28",
    displayDate: "April 28, 2026",
    category: "ai-general-news",
    companies: ["Google", "Pentagon", "OpenAI", "xAI"],
    title: "Google and Pentagon Reportedly Agree on Deal for 'Any Lawful' Use of AI",
    url: "https://www.theverge.com/ai-artificial-intelligence/919494/google-pentagon-classified-ai-deal",
    summary:
      "The Verge reported that Google signed a classified agreement allowing its AI models to be used for any lawful government purpose, with stated limits around domestic mass surveillance and autonomous weapons. For teams watching the AI tooling market, the story matters because it signals that frontier-model providers are becoming long-term government infrastructure vendors, not just consumer or enterprise software companies.",
  },
  {
    source: "Anthropic",
    date: "2026-04-28",
    displayDate: "April 28, 2026",
    category: "ai-general-news",
    companies: ["Anthropic", "Adobe", "Autodesk", "Blender", "Canva"],
    title: "Anthropic Adds Claude Connectors for Adobe, Blender, Autodesk, and Other Creative Tools",
    url: "https://www.anthropic.com/news/claude-for-creative-work",
    summary:
      "Anthropic announced Claude for Creative Work, a set of connectors that lets Claude work inside creative and production tools including Adobe Creative Cloud, Autodesk Fusion, Blender, Ableton, Affinity, SketchUp, and Splice. The update matters for AI-assisted teams because it expands MCP-style agent workflows beyond coding into design, 3D modeling, music, and asset pipelines, where automation can remove repetitive production steps without replacing human judgment.",
  },
  {
    source: "GitHub Blog",
    date: "2026-04-27",
    displayDate: "April 27, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "GitHub Copilot Is Moving to Usage-Based Billing on June 1",
    url: "https://github.blog/news-insights/company-news/github-copilot-is-moving-to-usage-based-billing/",
    summary:
      "GitHub announced that all Copilot plans will shift to AI-credit billing on June 1, 2026, while base subscription prices stay the same. Code completions and Next Edit Suggestions remain included, but chat, agent, and review usage will be metered more explicitly. For individuals and engineering managers, this changes how Copilot costs need to be forecast, monitored, and governed across teams.",
  },
  {
    source: "GitHub Changelog",
    date: "2026-04-27",
    displayDate: "April 27, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "Copilot Code Review Will Consume GitHub Actions Minutes on Private Repositories",
    url: "https://github.blog/changelog/2026-04-27-github-copilot-code-review-will-start-consuming-github-actions-minutes-on-june-1-2026/",
    summary:
      "GitHub said Copilot code review will begin consuming GitHub Actions minutes for private repositories on June 1, 2026, in addition to being billed through Copilot AI Credits. The change gives engineering leads another reason to treat agentic review as infrastructure usage: teams will need to watch both Copilot spend and Actions-minute budgets when automated review becomes part of normal pull request flow.",
  },
  {
    source: "GitHub Changelog",
    date: "2026-04-27",
    displayDate: "April 27, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "Copilot Cloud Agent Startup Time Improved by More Than 20%",
    url: "https://github.blog/changelog/2026-04-27-copilot-cloud-agent-starts-20-faster-with-actions-custom-images/",
    summary:
      "GitHub says Copilot's cloud agent now starts more than 20% faster because its runner environment is being prebuilt with GitHub Actions custom images. The update is small on paper but meaningful in practice: if agent sessions spin up faster, issue-to-code loops tighten and agent workflows become easier to use as a routine part of development instead of a slower fallback path.",
  },
  {
    source: "OpenAI",
    date: "2026-04-27",
    displayDate: "April 27, 2026",
    category: "ai-general-news",
    companies: ["OpenAI", "Microsoft", "Amazon"],
    title: "The Next Phase of the Microsoft OpenAI Partnership",
    url: "https://openai.com/index/next-phase-of-microsoft-partnership/",
    summary:
      "OpenAI said its amended Microsoft agreement now lets OpenAI serve products across any cloud provider while keeping Azure as its primary launch platform. For developers and enterprise teams, the practical signal is that model distribution and infrastructure are becoming less exclusive and more multi-cloud, which should matter for how AI tools get embedded into existing engineering stacks.",
  },
  {
    source: "OpenAI",
    date: "2026-04-27",
    displayDate: "April 27, 2026",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "OpenAI Reaches FedRAMP Moderate for ChatGPT Enterprise and Its API Platform",
    url: "https://openai.com/index/openai-available-at-fedramp-moderate/",
    summary:
      "OpenAI announced FedRAMP 20x Moderate authorization for ChatGPT Enterprise and the OpenAI API Platform, giving U.S. agencies a clearer path to use managed OpenAI products for research, drafting, translation, analysis, citizen-service workflows, and internal copilots. OpenAI also said agencies can access GPT-5.5 in the FedRAMP environment and will soon be able to reach Codex Cloud from FedRAMP ChatGPT Enterprise workspaces.",
  },
  {
    source: "OpenAI",
    date: "2026-04-26",
    displayDate: "April 26, 2026",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "OpenAI Publishes Updated Principles for How It Intends to Build and Deploy AI",
    url: "https://openai.com/index/our-principles/",
    summary:
      "OpenAI published a new principles document centered on democratization, empowerment, universal prosperity, resilience, and adaptability. The update is notable because it ties frontier model progress more directly to infrastructure buildout, security, and broad deployment, giving teams a clearer read on how OpenAI frames tradeoffs between rapid product shipping and system-level safeguards.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-24",
    displayDate: "April 24, 2026",
    category: "ai-general-news",
    companies: ["Google", "Anthropic"],
    title: "Google Plans Up to $40B More for Anthropic in Cash and Compute",
    url: "https://techcrunch.com/2026/04/24/google-to-invest-up-to-40b-in-anthropic-in-cash-and-compute/",
    summary:
      "TechCrunch reported that Alphabet plans to invest up to $40 billion more in Anthropic, with $10 billion committed immediately and up to $30 billion tied to performance targets. The deal deepens the unusual competitor-partner dynamic in frontier AI, where model labs increasingly depend on rival cloud providers for the compute needed to train and run advanced systems.",
  },
  {
    source: "Anthropic",
    date: "2026-04-24",
    displayDate: "April 24, 2026",
    category: "ai-general-news",
    companies: ["Anthropic", "NEC"],
    title: "Anthropic and NEC Partner to Build Japan's Largest AI Engineering Workforce",
    url: "https://www.anthropic.com/news/anthropic-nec?_bhlid=0bb303b3c2c14ba559c9aa85ea1de24a679d8ec9",
    summary:
      "Anthropic announced that NEC will roll out Claude to roughly 30,000 NEC Group employees worldwide as part of a long-term partnership focused on AI-native engineering and industry-specific products for Japan. The deal is notable for software teams because it frames Claude not just as a chatbot, but as shared engineering infrastructure embedded across a large enterprise workforce.",
  },
  {
    source: "About Amazon",
    date: "2026-04-24",
    displayDate: "April 24, 2026",
    category: "ai-general-news",
    companies: ["Amazon", "Meta"],
    title: "Meta Signs AWS Graviton Deal to Power Agentic AI Workloads",
    url: "https://press.aboutamazon.com/2026/4/meta-signs-agreement-with-aws-to-power-agentic-ai-on-aws-graviton-chips",
    summary:
      "Amazon said Meta will deploy AWS Graviton processors at scale, starting with tens of millions of cores, to support next-generation agentic AI. The announcement matters beyond infrastructure finance because it highlights a shift in AI system design: inference-heavy agent workloads such as code generation, search, and multi-step orchestration are driving fresh demand for CPU capacity, not just training GPUs.",
  },
  {
    source: "Anthropic",
    date: "2026-04-24",
    displayDate: "April 24, 2026",
    category: "ai-general-news",
    companies: ["Anthropic"],
    title: "Anthropic Tests Claude-Run Commerce in 'Project Deal' Marketplace Experiment",
    url: "https://www.anthropic.com/features/project-deal",
    summary:
      "Anthropic published results from 'Project Deal,' an experiment where Claude-powered agents negotiated and completed small real-money marketplace transactions. While the test was narrow, it offers a concrete look at where autonomous agents may go next: beyond drafting and research into transaction-oriented workflows that require judgment, memory, and bounded decision-making.",
  },
  {
    source: "CNBC",
    date: "2026-04-24",
    displayDate: "April 24, 2026",
    category: "new-models",
    companies: ["DeepSeek"],
    title: "DeepSeek Releases V4 Preview — Open-Source, 1M-Token Context, at a Fraction of the Cost",
    url: "https://www.cnbc.com/2026/04/24/deepseek-v4-llm-preview-open-source-ai-competition-china.html",
    summary:
      "Chinese AI startup DeepSeek launched preview versions of its V4 model family, including V4 Pro (1.6T total / 49B active params) and V4 Flash (284B total / 13B active params). V4 is the first open model family built from the ground up around million-token contexts as a default, using a Hybrid Attention Architecture that significantly reduces KV cache usage. The models are open-source and available via the DeepSeek API starting today, priced at $0.14–$1.74 per million input tokens depending on tier.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-23",
    displayDate: "April 23, 2026",
    category: "new-models",
    companies: ["OpenAI"],
    title: "OpenAI Releases GPT-5.5, Its Fastest and Most Capable Model Yet",
    url: "https://techcrunch.com/2026/04/23/openai-chatgpt-gpt-5-5-ai-model-superapp/",
    summary:
      "OpenAI released GPT-5.5, its newest frontier model, just six weeks after GPT-5.4 — a rapid cadence underscoring intense competition among AI labs. GPT-5.5 scores 88.7% on SWE-bench and 92.4% on MMLU, with a 60% reduction in hallucinations versus its predecessor. The model handles multi-step agentic workflows with less user input and is rolling out to Plus, Pro, Business, and Enterprise ChatGPT users, while also powering Codex on NVIDIA infrastructure. API pricing is $5 per million input tokens and $30 per million output tokens.",
  },
  {
    source: "9to5Mac",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["Google", "Apple"],
    title: "Google Confirms Gemini Will Power a Revamped, More Conversational Siri in 2026",
    url: "https://9to5mac.com/2026/04/22/google-teases-gemini-powered-siri-upgrade-during-cloud-next-keynote/",
    summary:
      "Google Cloud CEO Thomas Kurian confirmed at Cloud Next that Apple has selected Gemini as the foundation for the next generation of Apple Intelligence and Siri. Under a multi-year deal, Apple Foundation Models will be built on Gemini technology with Google Cloud handling training and inference. Phase 1 has already begun with iOS 26.4 bringing better context awareness to Siri; Phase 2 targets iOS 27 this September with full back-and-forth conversational Siri supporting 20+ exchanges and complex tasks.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["Google"],
    title: "Google Launches Gemini Enterprise Agent Platform at Cloud Next",
    url: "https://techcrunch.com/2026/04/22/google-makes-an-interesting-choice-with-its-new-agent-building-tool-for-enterprises/",
    summary:
      "At Google Cloud Next, CEO Sundar Pichai announced the Gemini Enterprise Agent Platform, Google's answer to Amazon Bedrock AgentCore and Microsoft Foundry. The tool is aimed at IT and technical teams building and managing agents at scale, and supports Google's own Gemini models alongside Anthropic's Claude Opus, Sonnet, and Haiku. A separate Gemini Enterprise app handles business-user workflows like scheduling and file management.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["Google"],
    title: "Google Cloud Launches TPU 8t and 8i — Two Specialized AI Chips to Compete with Nvidia",
    url: "https://techcrunch.com/2026/04/22/google-cloud-next-new-tpu-ai-chips-compete-with-nvidia/",
    summary:
      "Google announced its eighth-generation TPU family at Cloud Next, splitting the chip into two purpose-built designs: the TPU 8t for model training and the TPU 8i for inference. Google claims up to 3x faster training, 80% better performance per dollar versus prior generations, and the ability to cluster 1 million-plus TPUs together. The chips supplement rather than replace Nvidia hardware in Google Cloud's fleet.",
  },
  {
    source: "VentureBeat",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "OpenAI Unveils Workspace Agents as Successor to Custom GPTs for Enterprises",
    url: "https://venturebeat.com/orchestration/openai-unveils-workspace-agents-a-successor-to-custom-gpts-for-enterprises-that-can-plug-directly-into-slack-salesforce-and-more",
    summary:
      "OpenAI announced Workspace Agents, replacing Custom GPTs as its primary enterprise agent product. Agents can be created and accessed from ChatGPT and embedded directly into Slack, Salesforce, and other third-party platforms. Users can communicate with agents across disparate channels and grant them access to data from connected apps, positioning them as persistent workflow participants rather than standalone chatbot sessions.",
  },
  {
    source: "VentureBeat",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "ai-general-news",
    companies: ["Google"],
    title: "Google Launches Deep Research and Deep Research Max with MCP Support and Private Data Access",
    url: "https://venturebeat.com/technology/googles-new-deep-research-and-deep-research-max-agents-can-search-the-web-and-your-private-data",
    summary:
      "Google unveiled two new API-accessible research agents built on Gemini 3.1 Pro. Deep Research is optimized for speed in interactive apps; Deep Research Max uses extended test-time compute for exhaustive background research, scoring 93.3% on DeepSearchQA. Both agents add Model Context Protocol support, letting them query private databases and third-party enterprise data sources alongside the open web, plus native chart and infographic generation inside reports.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "mythos-news",
    companies: ["Anthropic"],
    title: "Unauthorized Group Gained Access to Anthropic's Exclusive Cyber Tool Mythos Through Third-Party Contractor",
    url: "https://techcrunch.com/2026/04/21/unauthorized-group-has-gained-access-to-anthropics-exclusive-cyber-tool-mythos-report-claims/",
    summary:
      "Bloomberg reported that members of a private Discord channel—interested in unreleased AI models—gained access to Mythos on the same day it was publicly announced, exploiting credentials held by a third-party contractor working for Anthropic. The group guessed the model's online location based on Anthropic's known URL patterns, provided screenshots and a live demo to Bloomberg, and has been using the model regularly since. Anthropic confirmed it is investigating but said it has found no evidence of impact to its own systems.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "ai-general-news",
    companies: ["SpaceX", "xAI"],
    title: "SpaceX Partners with Cursor and Holds Option to Acquire the Coding AI Startup for $60B",
    url: "https://techcrunch.com/2026/04/21/spacex-is-working-with-cursor-and-has-an-option-to-buy-the-startup-for-60-billion/",
    summary:
      "SpaceX announced a partnership with Cursor to co-develop a 'next-generation coding and knowledge work AI,' pairing Cursor's developer distribution with SpaceX's Colossus supercomputer. The deal includes an option to acquire Cursor for $60 billion later this year, up from a $50 billion valuation Cursor was eyeing in an imminent funding round. The move comes as SpaceX preps for its IPO and as Cursor and xAI chip resources grow closer—two senior Cursor engineering leads departed to join xAI earlier this month.",
  },
  {
    source: "Ars Technica",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "Mozilla"],
    title: "Mozilla: Mythos Found 271 Security Vulnerabilities in Firefox 150",
    url: "https://arstechnica.com/ai/2026/04/mozilla-anthropics-mythos-found-271-zero-day-vulnerabilities-in-firefox-150/",
    summary:
      "Mozilla reported that early access to Anthropic's Mythos Preview allowed its security team to identify 271 previously unknown security vulnerabilities in the Firefox 150 codebase before release. According to Mozilla's CTO, the model's findings were comparable to elite human security research, but delivered much faster.",
  },
  {
    source: "Anthropic",
    date: "2026-04-16",
    displayDate: "April 16, 2026",
    category: "new-models",
    companies: ["Anthropic"],
    title: "Introducing Claude Opus 4.7",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    summary:
      "Anthropic positioned Claude Opus 4.7 as a direct upgrade for advanced software engineering and long-running agentic work, with stronger instruction following, better multimodal handling, and new deployment safeguards informed by its Mythos-class safety work.",
  },
  {
    source: "Level Up Coding",
    date: "2026-04-12",
    displayDate: "April 12, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "Google", "Microsoft", "AWS", "Apple"],
    title: "Mythos Used by Major Tech Firms Found Bugs Across Every Major OS",
    url: "https://levelup.gitconnected.com/anthropics-new-ai-found-bugs-in-every-major-os-and-browser-and-they-re-not-releasing-it-6cae9ca4fa47",
    summary:
      "According to Level Up Coding, companies such as Apple, Google, Microsoft, and AWS ran Mythos through Project Glasswing to analyze operating systems and browser code. The model identified high-severity vulnerabilities across all major platforms, including cases where automated tools and human reviewers had failed for years.",
  },
  {
    source: "VentureBeat",
    date: "2026-04-10",
    displayDate: "April 10, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "Microsoft", "AWS", "Apple", "Cisco"],
    title: "Enterprise Partners Ran Mythos Against Critical Infrastructure",
    url: "https://venturebeat.com/security/mythos-detection-ceiling-security-teams-new-playbook",
    summary:
      "VentureBeat reported that companies participating in Anthropic's Project Glasswing, including Cisco, Microsoft, AWS, Apple, Palo Alto Networks, and the Linux Foundation, had been running Mythos against their own infrastructure and key open-source dependencies. These tests revealed long-standing vulnerabilities, including bugs that had survived decades of human review.",
  },
  {
    source: "Forbes",
    date: "2026-04-08",
    displayDate: "April 8, 2026",
    category: "mythos-news",
    companies: ["Anthropic"],
    title: "Fortune 500 and Open-Source Maintainers Found Critical Zero-Days",
    url: "https://www.forbes.com/sites/jonmarkman/2026/04/08/what-is-claude-mythos-and-why-anthropic-wont-let-anyone-use-it/",
    summary:
      "Forbes detailed how organizations with access to Mythos discovered thousands of zero-day vulnerabilities across major operating systems, browsers, and widely used libraries. In multiple cases, Mythos was also able to produce working exploits after initial discovery, increasing concern about how easily the findings could be weaponized.",
  },
  {
    source: "GitHub Blog",
    date: "2026-03-19",
    displayDate: "March 19, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "How Squad Runs Coordinated AI Agents Inside Your Repository",
    url: "https://github.blog/ai-and-ml/github-copilot/how-squad-runs-coordinated-ai-agents-inside-your-repository/",
    summary:
      "GitHub described Squad as a repository-native multi-agent workflow that uses shared project memory, specialist agents, and explicit reviewer separation to keep orchestration inspectable instead of hiding everything inside one chat loop.",
  },
  {
    source: "OpenAI",
    date: "2025-04-14",
    displayDate: "April 14, 2025",
    category: "new-models",
    companies: ["OpenAI"],
    title: "Introducing GPT-4.1 in the API",
    url: "https://openai.com/index/gpt-4-1/",
    summary:
      "OpenAI introduced GPT-4.1, GPT-4.1 mini, and GPT-4.1 nano with major gains in coding, instruction following, and long-context handling, positioning the family as lower-cost, more reliable infrastructure for agentic applications.",
  },
  {
    source: "OpenAI",
    date: "2025-03-11",
    displayDate: "March 11, 2025",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "New Tools for Building Agents",
    url: "https://openai.com/index/new-tools-for-building-agents/",
    summary:
      "OpenAI announced the Responses API, built-in web search, file search, computer use, and an Agents SDK, framing them as the first coordinated building blocks for production agent development and future migration away from the Assistants API.",
  },
  {
    source: "Anthropic",
    date: "2025-02-24",
    displayDate: "February 24, 2025",
    category: "new-models",
    companies: ["Anthropic"],
    title: "Claude 3.7 Sonnet and Claude Code",
    url: "https://www.anthropic.com/news/claude-3-7-sonnet",
    summary:
      "Anthropic launched Claude 3.7 Sonnet as a hybrid reasoning model and paired it with Claude Code, a research-preview coding tool designed to search code, edit files, run tests, and collaborate directly from the terminal.",
  },
  {
    source: "GitHub Blog",
    date: "2024-05-21",
    displayDate: "May 21, 2024",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "Introducing GitHub Copilot Extensions",
    url: "https://github.blog/news-insights/product-news/introducing-github-copilot-extensions/",
    summary:
      "GitHub introduced Copilot Extensions to pull partner tools and internal services into Copilot Chat, aiming to reduce context switching by letting developers query, act, and deploy across their stack from natural-language workflows in GitHub and VS Code.",
  },
];
