(function () {
  const latestUpdates = [
    {
      source: "Visual Studio Code",
      date: "2026-06-03",
      displayDate: "June 3, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Visual Studio Code", "GitHub Copilot", "Agents window", "Agent sessions"],
      title: "VS Code 1.124 Adds More Agents Window Session Controls",
      url: "https://code.visualstudio.com/updates/v1_124",
      summary:
        "Microsoft's VS Code 1.124 iteration notes add multi-chat support for local sessions in the Agents window, background send with Alt+Enter or Alt-click Send, keyboard shortcuts for jumping between sessions, and a bulk-close command for session cleanup. The release is smaller than the 1.123 stable notes, but it continues the same direction: agent work in VS Code is becoming a multi-session workspace that needs fast switching, background task kickoff, and predictable session management. For Copilot users, the practical watch item is whether these controls make parallel local agent workflows easier to supervise without losing track of active work.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-03",
      displayDate: "June 3, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot CLI", "Voice input", "Prompt scheduling", "Rubber duck"],
      title: "GitHub Updates Copilot CLI With Voice Input, Rubber Duck Review, and Experimental Scheduling",
      url: "https://github.blog/changelog/2026-06-02-copilot-cli-improved-ui-rubber-duck-prompt-scheduling-and-voice-input/",
      summary:
        "GitHub's Copilot CLI refresh adds generally available voice input and a built-in rubber duck critic agent, while the redesigned terminal UI and prompt scheduling commands are available through the experimental mode. The June 3 editor note clarifies that scheduling is experimental rather than generally available. For teams adopting terminal-based agents, this update matters because Copilot CLI is moving toward a richer agent console with session tabs, local voice transcription, scheduled follow-up prompts, accessibility improvements, and second-opinion review before changes land.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-03",
      displayDate: "June 3, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Visual Studio Code", "Agents window", "BYOK", "Agent Host Protocol"],
      title: "GitHub Summarizes May Copilot Updates for VS Code Agents",
      url: "https://github.blog/changelog/2026-06-03-github-copilot-in-visual-studio-code-may-releases/",
      summary:
        "GitHub's June 3 changelog recaps the May and early June Copilot updates in VS Code, including the Agents window preview in Stable, remote agent sessions over SSH or Dev Tunnels, Agent Host Protocol work, session sync, Chronicle commands, and side-by-side agent sessions. The release also expands bring-your-own-key model support to air-gapped environments and adds finer model controls for utility tasks, reasoning effort, and token visibility. For VS Code users, the signal is that agent work is becoming a persistent, multi-session development surface where model governance, terminal safety, remote execution, and searchable session history matter as much as inline completions.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot SDK", "MCP", "OpenTelemetry", "Developer tools"],
      title: "GitHub Makes the Copilot SDK Generally Available",
      url: "https://github.blog/changelog/2026-06-02-copilot-sdk-is-now-generally-available/",
      summary:
        "GitHub made the Copilot SDK generally available, giving teams stable programmatic access to the agent runtime behind Copilot for planning, tool invocation, file edits, streaming, and multi-turn sessions. The SDK is available across Node.js/TypeScript, Python, Go, .NET, Rust, and Java, and supports MCP tools, prompt customization, OpenTelemetry tracing, multiple authentication paths, cloud or remote sessions, and pre/post tool hooks. For engineering teams, this turns Copilot from an IDE-only assistant into embeddable agent infrastructure for internal tools, CI/CD assistants, customer-facing developer features, and governed automation.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot CLI", "Sandboxes", "Microsoft MXC", "Agent security"],
      title: "GitHub Puts Copilot Cloud and Local Sandboxes Into Public Preview",
      url: "https://github.blog/changelog/2026-06-02-cloud-and-local-sandboxes-for-github-copilot-now-in-public-preview/",
      summary:
        "GitHub put cloud and local sandboxes for Copilot into public preview, giving agent sessions isolated places to run commands, touch files, and use network access under defined policies. Local sandboxing can be enabled inside a session with `/sandbox enable` and is built on Microsoft MXC across macOS, Linux, and Windows, while cloud sandboxes launch ephemeral Linux environments through `copilot --cloud` and inherit Copilot cloud agent policies. For teams evaluating coding agents, sandboxing is a practical control layer: agent autonomy only scales if filesystem, network, identity, policy, and enterprise management boundaries are clear.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "new-models",
      companies: ["GitHub", "GitHub Copilot", "Google", "Gemini 3.1 Pro", "Gemini 3.5 Flash", "Model governance"],
      title: "GitHub Expands Gemini Model Access Across Copilot Surfaces",
      url: "https://github.blog/changelog/2026-06-02-gemini-models-in-copilot-cli-cloud-agent-and-the-copilot-app/",
      summary:
        "GitHub added Gemini 3.1 Pro in preview and Gemini 3.5 Flash across more Copilot surfaces, including Copilot CLI, Copilot cloud agent, the Copilot app technical preview, and the Copilot SDK. Gemini 3.1 Pro is available across Student, Pro, Pro+, Business, and Enterprise plans, while Gemini 3.5 Flash is available for Pro, Pro+, Business, and Enterprise subscribers, with Business and Enterprise admins required to enable the relevant model policy. For model selection guidance, this reinforces Copilot as a multi-model platform where admins need to track surface availability, preview status, plan eligibility, and policy gates before recommending a model for production workflows.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "new-models",
      companies: ["GitHub", "GitHub Copilot", "Microsoft", "MAI-Code-1-Flash", "VS Code", "Coding models"],
      title: "Microsoft's MAI-Code-1-Flash Begins Rolling Out in GitHub Copilot",
      url: "https://github.blog/changelog/2026-06-02-mai-code-1-flash-is-now-available-for-github-copilot/",
      summary:
        "GitHub said MAI-Code-1-Flash, Microsoft's new small-tier coding model, is beginning to roll out in GitHub Copilot starting with Visual Studio Code. The model is tuned specifically for Copilot, positioned for lightweight coding workflows, and will gradually expand across Copilot Free, Pro, Pro+, and Max plans after an initial limited rollout. For developers, this is another sign that routine coding work is being routed toward specialized, lower-cost models while larger frontier models are reserved for higher-complexity planning, review, and reasoning tasks.",
    },
    {
      source: "Microsoft 365 Blog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Microsoft 365 Copilot", "Scout", "Personal agents", "Knowledge work"],
      title: "Microsoft Introduces Scout as an Always-On Personal Agent for Microsoft 365",
      url: "https://www.microsoft.com/en-us/microsoft-365/blog/2026/06/02/introducing-microsoft-scout-your-always-on-personal-agent/",
      summary:
        "Microsoft introduced Scout, an always-on personal agent for Microsoft 365 that is designed to stay grounded in the apps and work context people already use. The announcement matters for AI-workflow tracking because it pushes Copilot-style assistance beyond prompt-response chat into persistent, user-specific agency across documents, communication, and daily work. For teams adopting AI tools, the practical question is how to govern memory, permissions, delegation, and handoff when agents become a standing part of the productivity stack instead of a one-off assistant.",
    },
    {
      source: "Microsoft Blog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "CoreAI", "GitHub", "Azure AI Foundry", "Fabric", "Enterprise agents"],
      title: "Microsoft Frames Azure, GitHub, Foundry, Fabric, and Copilot as One Agent System",
      url: "https://blogs.microsoft.com/blog/2026/06/02/ai-alone-wont-change-your-business-the-system-running-it-will/",
      summary:
        "Microsoft's CoreAI group argued that enterprise AI value depends on the operating system around agents, not just the model. The post says Microsoft is bringing Azure, GitHub, Microsoft IQ, Fabric, Foundry, Windows, Microsoft Security, and Microsoft 365 together as a single system for deploying agents at enterprise scale. For engineering and operations teams, the signal is that agent adoption increasingly depends on identity, data access, orchestration, security controls, developer workflows, and observability across the full stack.",
    },
    {
      source: "OpenAI",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["OpenAI", "Codex", "Plugins", "Sites", "Annotations", "Knowledge work"],
      title: "OpenAI Expands Codex With Role-Specific Plugins, Sites, and Annotations",
      url: "https://openai.com/index/codex-for-every-role-tool-workflow/",
      summary:
        "OpenAI introduced new Codex capabilities aimed beyond software teams: role-specific plugins, workspace-shareable Sites, and in-place annotations for refining generated work. The launch includes six plugin bundles for data analytics, creative production, product design, sales, public equity investing, and investment banking, with OpenAI saying the bundles span 62 popular apps and 110 skills. For teams using coding agents, the signal is that Codex is becoming a broader work-execution layer where connectors, reusable skills, review surfaces, and shareable outputs matter as much as code generation.",
    },
    {
      source: "OpenAI",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["OpenAI", "Codex", "Knowledge work", "AI adoption", "Workflow automation"],
      title: "OpenAI Says Codex Has Passed 5 Million Weekly Active Users",
      url: "https://openai.com/index/codex-for-knowledge-work/",
      summary:
        "OpenAI released a report describing Codex as a productivity tool for more than developers, saying Codex now has over 5 million weekly active users and that knowledge workers make up about 20 percent of usage while growing faster than developers. OpenAI says non-developer use is concentrated in reports, spreadsheets, presentations, contracts, research, data analysis, workflow automation, and lightweight internal tools. For AI adoption planning, this broadens the practical evaluation question from whether agents write code well to whether teams can govern parallel agent work that creates business artifacts across roles.",
    },
    {
      source: "GitHub Blog",
      date: "2026-06-02",
      displayDate: "June 2, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot app", "Agent Merge", "Copilot SDK", "Copilot code review"],
      title: "GitHub Introduces Copilot App as an Agent-Native Desktop Experience",
      url: "https://github.blog/news-insights/product-news/github-copilot-app-the-agent-native-desktop-experience/",
      summary:
        "At Microsoft Build, GitHub introduced the Copilot app technical preview as a desktop control center for agentic development across issues, pull requests, sessions, canvases, sandboxes, and review workflows. GitHub says sessions run in separate git worktrees, Agent Merge can help carry pull requests through checks and review, and the Copilot SDK is generally available across major languages for teams embedding the same runtime in their own tools. For VS Code and GitHub users, this makes agent orchestration, validation, sandbox policy, cost tiers, and human review flow central parts of the coding-agent experience.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-01",
      displayDate: "June 1, 2026",
      category: "new-models",
      companies: ["GitHub", "GitHub Copilot", "Auto model selection", "Evaluation models", "Copilot Free"],
      title: "GitHub Adds Evaluation Models to Copilot Auto for Individual Plans",
      url: "https://github.blog/changelog/2026-06-01-evaluation-models-in-auto-for-individual-plans",
      summary:
        "GitHub updated Copilot Auto model selection for Individual plans so Auto can now draw from evaluation models such as Goldeneye and Raptor in addition to generally available models. The change applies to Copilot Free, Pro, and Pro+ users, while Business and Enterprise continue using only generally available models through Auto. For model guidance, the practical takeaway is to treat Auto as a broader experimental routing surface for individual users, but to keep enterprise recommendations tied to admin-approved GA models and actual client availability.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-06-01",
      displayDate: "June 1, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "AI Credits", "Copilot code review", "Copilot Max", "Actions runners"],
      title: "GitHub Activates Usage-Based Copilot Billing and New Budget Controls",
      url: "https://github.blog/changelog/2026-06-01-updates-to-github-copilot-billing-and-plans/",
      summary:
        "GitHub's June 1 Copilot update makes usage-based billing active across Copilot plans, with usage measured through GitHub AI Credits and Copilot code review now consuming GitHub Actions minutes as well. The release also adds organization-level default runner configuration for Copilot code review, generally available user-level budgets for organizations and enterprises, and Copilot Max upgrades for existing Student, Pro, and Pro+ subscribers. For teams using coding agents heavily, the practical takeaway is to treat Copilot adoption as a governed operational cost: configure budgets, review runner defaults, and decide where agentic workflows are worth the added credit and Actions spend.",
    },
    {
      source: "Anthropic",
      date: "2026-06-01",
      displayDate: "June 1, 2026",
      category: "ai-general-news",
      companies: ["Anthropic", "Claude", "IPO", "SEC", "Enterprise AI"],
      title: "Anthropic Confidentially Files Draft S-1 for a Proposed IPO",
      url: "https://www.anthropic.com/news/confidential-draft-s1-sec",
      summary:
        "Anthropic said it confidentially submitted a draft Form S-1 registration statement to the U.S. Securities and Exchange Commission for a proposed initial public offering of common stock. The announcement says the share count and price have not been set, and that the offering remains dependent on SEC review, market conditions, and other factors. For AI-tool buyers, the signal is that frontier-model labs are moving deeper into public-market scrutiny, where revenue durability, infrastructure commitments, safety posture, enterprise adoption, and margin pressure around products such as Claude and Claude Code will become harder to separate.",
    },
    {
      source: "TechCrunch",
      date: "2026-06-01",
      displayDate: "June 1, 2026",
      category: "ai-general-news",
      companies: ["WindBorne Systems", "WeatherMesh", "ECMWF", "NOAA", "AI weather forecasting"],
      title: "TechCrunch Reports WindBorne's WeatherMesh-6 Is Challenging Traditional Forecasting",
      url: "https://techcrunch.com/2026/06/01/this-ai-weather-startup-is-out-forecasting-government-agencies/",
      summary:
        "TechCrunch reported that WindBorne Systems released WeatherMesh-6, an AI weather model the company says can forecast key variables more frequently and accurately than leading traditional systems, using both model improvements and balloon-collected sensor data. The report says the model produces hourly forecasts and reaches 3 km resolution in Europe and the continental U.S., while WindBorne continues selling data to NOAA and U.S. military customers. The broader AI signal is that domain agents and models may need proprietary data pipelines as much as model architecture: forecast quality, data assimilation, and operational integration become the defensible advantage.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-05-29",
      displayDate: "May 29, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot usage metrics", "AI adoption", "Enterprise analytics"],
      title: "GitHub Adds AI Adoption Cohorts to Copilot Usage Metrics",
      url: "https://github.blog/changelog/2026-05-29-copilot-usage-metrics-api-adds-cohorts-for-ai-adoption/",
      summary:
        "GitHub added AI adoption phase fields to Copilot usage metrics, classifying engaged users over a rolling 28-day window into code-first, agent-first, and multi-agent cohorts based on the Copilot surfaces they use. Enterprise and organization reports can now group metrics such as engagement, interactions, generated and accepted code, pull requests, review activity, and median time to merge by those phases. For engineering leaders, this turns Copilot rollout measurement from simple active-user counting into a maturity model that can guide enablement, budget decisions, and training for agentic development.",
    },
    {
      source: "Anthropic",
      date: "2026-05-28",
      displayDate: "May 28, 2026",
      category: "ai-general-news",
      companies: ["Anthropic", "Claude", "Claude Opus 4.8", "Claude Code", "Dynamic workflows", "Agentic coding"],
      title: "Anthropic Launches Claude Opus 4.8 With Stronger Coding and Agent Workflows",
      url: "https://www.anthropic.com/news/claude-opus-4-8",
      summary:
        "Anthropic released Claude Opus 4.8, highlighting stronger coding, agentic task performance, reasoning, knowledge-work behavior, and a lower tendency to leave flaws or uncertainty unflagged. The release also adds dynamic workflows in research preview for Claude Code, letting Claude plan larger work, run many parallel subagents, verify outputs, and handle codebase-scale migrations for Enterprise, Team, and Max plans. For teams comparing development agents, the important signal is that frontier models are being judged less on chat polish and more on long-running execution, self-checking, cost control, and whether they can operate across large repositories without losing judgment.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-05-28",
      displayDate: "May 28, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Anthropic", "Claude Opus 4.8", "VS Code", "Copilot CLI"],
      title: "GitHub Makes Claude Opus 4.8 Available in Copilot",
      url: "https://github.blog/changelog/2026-05-28-claude-opus-4-8-is-generally-available-for-github-copilot/",
      summary:
        "GitHub made Claude Opus 4.8 generally available in Copilot, with access planned across Visual Studio Code chat, ask, edit, and agent modes, Visual Studio, Copilot CLI, Copilot cloud agent, the GitHub Copilot app, github.com, mobile, JetBrains, Xcode, and Eclipse. The model is rolling out gradually for Pro+, Business, and Enterprise users, and Business or Enterprise administrators need to enable the model policy in Copilot settings. The practical takeaway is that Copilot is becoming a multi-model agent platform where model governance, rollout timing, and premium-request cost multipliers matter as much as raw model quality.",
    },
    {
      source: "Anthropic",
      date: "2026-05-28",
      displayDate: "May 28, 2026",
      category: "ai-general-news",
      companies: ["Anthropic", "Claude", "Claude Code", "Cowork", "AWS", "Google Cloud", "Microsoft Azure"],
      title: "Anthropic Raises $65 Billion as Claude Demand Pushes Compute Expansion",
      url: "https://www.anthropic.com/news/series-h",
      summary:
        "Anthropic announced a $65 billion Series H at a $965 billion post-money valuation, saying the funding will support safety and interpretability research, compute expansion, Claude product growth, and enterprise partnerships. The announcement says the round includes previously committed hyperscaler investments, strategic memory and chip partners, recent capacity agreements with Amazon, Google and Broadcom, and SpaceX GPU capacity, while Claude is available across AWS, Google Cloud, and Microsoft Azure. For AI-tool buyers, this is a reminder that agent quality and availability are now tied directly to capital, cloud capacity, chip supply, and the economics of running Claude Code and Cowork at scale.",
    },
    {
      source: "Visual Studio Code",
      date: "2026-05-27",
      displayDate: "May 27, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Visual Studio Code", "GitHub Copilot", "Agents window", "AI customization"],
      title: "VS Code 1.123 Updates Agent Sessions and AI Customization Controls",
      url: "https://code.visualstudio.com/updates/v1_123",
      summary:
        "Microsoft's VS Code 1.123 release notes add several agent-facing refinements: the Agents window now shows sessions in a grid layout, agent feedback supports threaded replies, steering messages appear as their own chat turns, and parallel terminal-command completions are batched into a single notification. The release also updates the AI Customization management editor with a cleaner compact header. For VS Code users, the practical takeaway is that agent work is becoming easier to scan, steer, and review across longer sessions rather than being treated as a single chat transcript.",
    },
    {
      source: "OpenAI",
      date: "2026-05-27",
      displayDate: "May 27, 2026",
      category: "ai-general-news",
      companies: ["OpenAI", "Codex", "Thrive Holdings", "Crete", "Tax AI", "Agent evaluation"],
      title: "OpenAI Shows How Codex Can Drive Self-Improving Domain Agents",
      url: "https://openai.com/index/building-self-improving-tax-agents-with-codex/",
      summary:
        "OpenAI and Thrive Holdings described a Tax AI workflow for Crete accountants that uses practitioner corrections, production traces, targeted evals, and Codex-driven engineering tasks to improve a deployed tax-preparation agent over time. The system reportedly processed 7,000 returns during the pilot, saved practitioners about a third of preparation time, and raised measured field-completion quality as the season progressed. For developer teams, the practical lesson is that agent improvement needs more than prompts: production evidence, reviewed failure grouping, eval gates, human review, and scoped tool access are the operating model that turns coding agents into durable product infrastructure.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-27",
      displayDate: "May 27, 2026",
      category: "ai-general-news",
      companies: ["Cognition", "Devin", "AI coding agents", "OpenAI Codex", "Claude Code", "Windsurf"],
      title: "Cognition Raises $1 Billion as AI Coding Agent Market Stays Hot",
      url: "https://techcrunch.com/2026/05/27/ai-coding-startup-cognition-raises-1b-at-25b-pre-money-valuation/",
      summary:
        "TechCrunch reported that Cognition, maker of the Devin autonomous software engineer, raised more than $1 billion at a $25 billion pre-money valuation. The round is a signal that investors still see room for independent AI coding-agent companies even as frontier-model vendors push Claude Code, Codex, Jules, Copilot, and other first-party development agents. For buyers and engineering leaders, the important takeaway is to compare these tools on production outcomes, repository fit, governance, cost, and verification workflows rather than assuming the market will collapse into one bundled assistant.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-27",
      displayDate: "May 27, 2026",
      category: "ai-general-news",
      companies: ["Snowflake", "AWS", "Amazon", "Cortex AI", "Graviton", "AI infrastructure"],
      title: "Snowflake Signs $6 Billion AWS Deal as AI Workloads Drive Cloud Demand",
      url: "https://techcrunch.com/2026/05/27/in-more-good-news-for-amazon-snowflake-signs-6b-deal-with-aws-for-ai-cpu-chips/",
      summary:
        "TechCrunch covered Snowflake's new five-year, $6 billion AWS agreement, with AI demand and Snowflake Cortex AI usage highlighted as drivers of increased cloud spending. The story also points to a practical infrastructure shift: as AI moves from training into everyday automation and agent workloads, CPUs and cloud-native chips such as AWS Graviton become more important alongside GPUs. For teams deploying internal agents, the lesson is to budget for the full runtime stack, including data platforms, inference, orchestration, retrieval, logging, and routine compute that grows once agents become operational.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-27",
      displayDate: "May 27, 2026",
      category: "ai-general-news",
      companies: ["ElevenLabs", "AI music", "Generative media", "Licensing", "ElevenCreative"],
      title: "ElevenLabs Launches Music v2 With Licensed Commercial-Use Positioning",
      url: "https://techcrunch.com/2026/05/27/elevenlabss-new-music-generation-model-can-switch-genres-mid-track/",
      summary:
        "TechCrunch reported that ElevenLabs launched Music v2, a music-generation model that can change genres within a track, handle vocals and composition more reliably, and let creators regenerate selected song sections from prompts. ElevenLabs says the model is built on licensed data and cleared for commercial use, which matters as AI music companies face copyright scrutiny. For AI-tool users, the broader signal is that generative media products are competing not only on output quality but also on licensing, editability, API availability, and whether commercial teams can safely use the generated assets.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-05-26",
      displayDate: "May 26, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot Memory", "Copilot CLI", "Repository settings", "AI governance"],
      title: "GitHub Adds More Copilot Memory Controls Across Repositories and CLI",
      url: "https://github.blog/changelog/2026-05-26-copilot-memory-has-more-controls-for-deletion-scope-and-the-copilot-cli/",
      summary:
        "GitHub expanded Copilot Memory controls with clearer deletion guidance, a repository-level off switch, explicit scope labels when memory is captured, and `/memory` commands for Copilot CLI sessions. Copilot Memory remains in public preview for paid Copilot plans. For VS Code and agent users, this is a practical governance update: memory can improve continuity, but teams should decide where repository facts are allowed, who can review them, and when sensitive or outdated context should be removed.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-05-26",
      displayDate: "May 26, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Enterprise", "Model rules", "AI governance", "Cost controls"],
      title: "GitHub Adds Organization-Targeted Copilot Model Rules",
      url: "https://github.blog/changelog/2026-05-26-target-copilot-models-to-organizations-with-model-rules/",
      summary:
        "GitHub introduced targeted model rules in public preview for Copilot Business and Enterprise customers, letting enterprise owners allow specific Copilot models for selected organizations instead of relying only on enterprise-wide defaults. GitHub also refreshed the default model availability UI. The useful takeaway for teams is that model choice is becoming an admin-governed control surface: cost, risk, data policy, and task fit can now vary by organization rather than being a single blanket setting.",
    },
    {
      source: "Anthropic",
      date: "2026-05-26",
      displayDate: "May 26, 2026",
      category: "ai-general-news",
      companies: ["Anthropic", "Claude", "Korea", "Seoul office", "Enterprise AI", "Developer adoption"],
      title: "Anthropic Names Korea Representative Director Ahead of Seoul Office Opening",
      url: "https://www.anthropic.com/news/kiyoung-choi-representative-director-anthropic-korea",
      summary:
        "Anthropic appointed KiYoung Choi as Representative Director of Korea ahead of opening its Seoul office, saying Claude usage in Korea is more than 3.5 times what population size alone would predict and skews heavily toward technical and creative work. The announcement matters for AI-tool tracking because it shows frontier-model vendors moving from global product launches into local enterprise, startup, government, research, and developer-community support. For teams choosing agents and coding assistants, regional presence increasingly affects adoption, compliance conversations, partnerships, and implementation support.",
    },
    {
      source: "Visual Studio Code",
      date: "2026-05-20",
      displayDate: "May 20, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Visual Studio Code", "GitHub Copilot", "Agent Sessions", "Copilot setup"],
      title: "VS Code Refreshes Copilot Setup and Agent Guidance",
      url: "https://code.visualstudio.com/docs/copilot/overview",
      summary:
        "Microsoft's current VS Code Copilot docs now frame Copilot around agent sessions that can plan, edit, run commands, verify results, and move between editor, background, cloud, local, and third-party agent surfaces. The setup docs also note that new sign-ups for Copilot Pro, Pro+, and student plans remain temporarily paused while existing subscribers and eligible accounts can continue using the available plan paths. For this site, the practical update is to teach Copilot as an agent platform with policy, plan availability, and workspace-control checks rather than just a chat extension.",
    },
    {
      source: "Visual Studio Code",
      date: "2026-05-15",
      displayDate: "May 15, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Visual Studio Code", "GitHub Copilot", "Coding agents", "Model selection"],
      title: "VS Code Explains Why the Coding Harness Matters as Much as the Model",
      url: "https://code.visualstudio.com/blogs/2026/05/15/coding-harness",
      summary:
        "The VS Code team published a deeper explanation of the coding harness behind Copilot: the agent loop, tools, context handling, system prompts, terminal integration, debugging, source control, and evaluation layer that turn a model into a working developer experience. The useful takeaway is that model choice alone is no longer the right comparison point. Teams should evaluate whether their editor harness exposes the right tools safely, preserves context, supports multiple model providers, and verifies work before treating a newer model as an automatic upgrade.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-05-14",
      displayDate: "May 14, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Copilot app", "Agentic development", "Pull requests"],
      title: "GitHub Copilot App Enters Technical Preview",
      url: "https://github.blog/changelog/2026-05-14-github-copilot-app-is-now-available-in-technical-preview/",
      summary:
        "GitHub announced a technical preview of the GitHub Copilot app, a GitHub-native desktop experience for starting agentic sessions from issues, pull requests, prompts, or prior sessions, keeping work isolated, steering the agent, validating results, and landing changes through pull request review. Business and Enterprise access requires preview features and Copilot CLI policy enablement. This is relevant to VS Code users because Copilot's agent workflow is spreading beyond one editor surface into a coordinated GitHub-to-desktop-to-PR loop.",
    },
    {
      source: "Anthropic",
      date: "2026-05-25",
      displayDate: "May 25, 2026",
      category: "ai-general-news",
      companies: ["Anthropic", "Claude", "AI safety", "AI ethics", "AI governance", "Vatican"],
      title: "Anthropic Publishes Chris Olah's Remarks on Pope Leo XIV's AI Encyclical",
      url: "https://www.anthropic.com/news/chris-olah-pope-leo-encyclical",
      summary:
        "Anthropic published co-founder Chris Olah's remarks from the Vatican presentation of Pope Leo XIV's Magnifica Humanitas encyclical on AI. Olah argued that frontier labs operate under commercial, research, geopolitical, pride, and ambition pressures, making outside scrutiny from religious communities, civil society, scholars, governments, and other informed critics essential. The practical takeaway for AI builders is that safety cannot be treated as a lab-only discipline: labor displacement, global benefit-sharing, human flourishing, and uncertainty about model internals need broader review before agentic systems become deeply embedded in work and public life.",
    },
    {
      source: "AP News",
      date: "2026-05-25",
      displayDate: "May 25, 2026",
      category: "ai-general-news",
      companies: ["Vatican", "Anthropic", "AI regulation", "AI ethics", "Human dignity"],
      title: "Pope Leo XIV Calls for Robust AI Regulation in First Encyclical",
      url: "https://apnews.com/article/d92d0108730d146baa46da041b8523da",
      summary:
        "AP reported that Pope Leo XIV issued his first encyclical, Magnifica Humanitas, calling for stronger regulation of artificial intelligence and urging developers to prioritize the common good over profit. Anthropic co-founder Christopher Olah joined the Vatican presentation and welcomed the pope's concern. For AI builders and agent users, the important signal is that governance pressure is broadening beyond product safety teams: labor impact, war, human dignity, accountability, and concentration of power are becoming part of mainstream AI adoption debates.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-24",
      displayDate: "May 24, 2026",
      category: "ai-general-news",
      companies: ["Google Cloud", "Gemini", "AI security", "Shadow AI", "Enterprise governance"],
      title: "TechCrunch: Even Google Is Navigating AI Security in Real Time",
      url: "https://techcrunch.com/2026/05/24/everyone-is-navigating-ai-security-in-real-time-even-google/",
      summary:
        "TechCrunch used comments from Google Cloud COO Francis de Souza and recent Gemini API-key incidents to frame the enterprise AI security problem: companies need data strategy, platform governance, auditability, and consistent controls across clouds before agents roam internal systems. The piece also highlights practical risks around shadow AI, stale data repositories, API-key scope expansion, billing exposure, and delayed credential revocation. For this site's guidance, it reinforces that agent adoption should include permission review, budget caps, secret hygiene, and audit trails from the start.",
    },
    {
      source: "GitHub Blog",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "GitHub Copilot", "Gartner", "Enterprise AI Coding Agents", "Developer productivity"],
      title: "GitHub Says Copilot Was Named a Gartner Leader for Enterprise AI Coding Agents",
      url: "https://github.blog/ai-and-ml/github-copilot/github-recognized-as-a-leader-in-the-gartner-magic-quadrant-for-enterprise-ai-coding-agents-for-the-third-year-in-a-row/",
      summary:
        "GitHub said Gartner recognized GitHub as a Leader in the 2026 Magic Quadrant for Enterprise AI Coding Agents, emphasizing Copilot's breadth across IDEs, CLI, cloud agent work, code review, governance, and enterprise deployment. The useful takeaway for VS Code users is that Copilot is now being positioned as a managed agent platform rather than a single editor feature. That makes current model selection, policy controls, agent-session review, and usage monitoring more important than treating chat, completions, and background agents as separate tools.",
    },
    {
      source: "OpenAI",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "ai-general-news",
      companies: ["OpenAI", "Codex", "Gartner", "Enterprise AI Coding Agents", "Software development"],
      title: "OpenAI Says Gartner Named It a Leader in Enterprise AI Coding Agents",
      url: "https://openai.com/index/gartner-2026-agentic-coding-leader/",
      summary:
        "OpenAI published its response to Gartner's 2026 Magic Quadrant for Enterprise AI Coding Agents, saying Codex is now used by more than 4 million people each week and highlighting enterprise deployments at companies such as Cisco, Datadog, Dell Technologies, and NVIDIA. The practical signal for VS Code and Copilot users is that coding agents are being evaluated as an enterprise software category, not just as editor autocomplete. Teams should expect vendor comparisons to focus on repository reasoning, tool use, governance, deployment controls, and measurable software-delivery outcomes.",
    },
    {
      source: "OpenAI",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "ai-general-news",
      companies: ["OpenAI", "Codex", "Virgin Atlantic", "Enterprise software", "Testing", "Refactoring"],
      title: "Virgin Atlantic Uses Codex to Ship and Refactor Production Software Faster",
      url: "https://openai.com/index/virgin-atlantic",
      summary:
        "OpenAI's Virgin Atlantic case study says the airline used Codex to strengthen test coverage before a high-stakes mobile-app launch, ship with no P1 launch defects, and cut some legacy refactors from roughly two weeks to about 30 minutes. The relevant takeaway for developer teams is not just speed: mature Codex adoption is being framed around test coverage, defect reduction, refactoring safety, and delivery coordination. That is the same operating model this site's agent guidance recommends for production codebases: let agents accelerate work, but keep verification and release quality visible.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-23",
      displayDate: "May 23, 2026",
      category: "ai-general-news",
      companies: ["IBM", "Ferrari", "Formula One", "Enterprise AI", "Personalization", "Fan engagement"],
      title: "Ferrari Uses IBM AI to Turn Race Data Into Personalized Fan Experiences",
      url: "https://techcrunch.com/2026/05/23/ferrari-is-using-ai-to-create-f1-superfans/",
      summary:
        "TechCrunch reported that Ferrari and IBM are using AI in the Ferrari fan app to turn race data, engagement signals, and team storytelling into more personalized experiences. The app now includes AI-written race summaries, games, prediction features, and an AI companion, with Ferrari citing stronger race-weekend engagement after the IBM partnership. For AI product teams, the useful signal is that applied AI is moving beyond chat assistants into domain-specific customer experiences where data, trust, and repeat engagement matter as much as the model itself.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "ai-general-news",
      companies: ["NTSB", "Codex", "Synthetic media", "AI safety", "Transportation"],
      title: "NTSB Closes Some Dockets After AI-Recreated Pilot Voices Circulate Online",
      url: "https://techcrunch.com/2026/05/22/ai-is-being-used-to-resurrect-the-voices-of-dead-pilots/",
      summary:
        "TechCrunch reported that the National Transportation Safety Board temporarily removed public access to its docket system after people used public spectrogram and transcript data to recreate cockpit voice audio from a fatal UPS crash. The report says social posts referenced AI tools, including Codex, in the reconstruction workflow. For agent users, the important lesson is boundary-setting: capable coding and media tools can combine public technical artifacts into sensitive outputs, so teams need data-release review, misuse thinking, and human judgment around what should be reconstructed even when it is technically possible.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "ai-general-news",
      companies: ["AI startups", "Venture capital", "ARR", "Enterprise AI", "AI economics"],
      title: "TechCrunch Examines Inflated ARR Claims Across AI Startups",
      url: "https://techcrunch.com/2026/05/22/how-vcs-and-founders-use-inflated-arr-to-kingmake-ai-startups/",
      summary:
        "TechCrunch examined how some AI startups and investors blur annual recurring revenue with contracted or committed ARR, making growth look stronger before customers are fully onboarded or revenue is actually collected. The piece matters for enterprise AI buyers because inflated metrics can hide product-delivery risk, long implementation timelines, churn, and usage economics. For teams tracking AI tools, it is a reminder to look past headline valuations and ask whether adoption, retention, cost-to-serve, and production outcomes support the claimed momentum.",
    },
    {
      source: "Anthropic",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "mythos-news",
      companies: ["Anthropic", "Claude", "Mythos Preview", "Project Glasswing", "Open source security", "Cybersecurity"],
      title: "Anthropic Shares First Project Glasswing Results From AI-Assisted Security Scans",
      url: "https://www.anthropic.com/news/glasswing-initial-update",
      summary:
        "Anthropic's first Project Glasswing update says Claude Mythos Preview has helped roughly 50 partners find more than ten thousand high- or critical-severity vulnerabilities and has scanned more than 1,000 open-source projects. Anthropic says independent review of a subset found a 90.6% true-positive rate, while emphasizing that verification, coordinated disclosure, and patching are now the bottlenecks. For coding-agent users, the important signal is both promise and caution: stronger models can materially improve defensive code review, but high-impact security work still needs controlled release, human triage, and responsible disclosure.",
    },
    {
      source: "Fortune",
      date: "2026-05-22",
      displayDate: "May 22, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Anthropic", "Claude Code", "GitHub Copilot", "Copilot CLI", "AI cost governance"],
      title: "Fortune Highlights Enterprise AI Cost Pressure Around Claude Code and Copilot CLI",
      url: "https://fortune.com/2026/05/22/microsoft-ai-cost-problem-tokens-agents/",
      summary:
        "Fortune reported on the enterprise cost pressure behind Microsoft's reported move away from broad internal Claude Code licensing and toward GitHub Copilot CLI for many developers. The piece is useful less as a product-launch story than as a budget warning: agentic coding tools can shift teams from predictable seat pricing into usage-sensitive token and model costs. For this site's model guidance, that reinforces the current recommendation to start routine work on included or low-multiplier models, reserve frontier models for narrow high-value decisions, and monitor usage before June billing changes.",
    },
    {
      source: "OpenAI Help",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["OpenAI", "Codex", "ChatGPT", "Computer Use", "Goal mode", "AI agents"],
      title: "OpenAI Adds Appshots, Goal Mode GA, and Locked Computer Use to Codex",
      url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes",
      summary:
        "OpenAI's latest ChatGPT release notes add several Codex workflow updates: Appshots for attaching Mac app-window context, Goal mode generally available across the Codex app, IDE extension, and CLI, more precise in-app browser annotations, locked computer use for eligible Mac Computer Use users, and browser-use reliability improvements. For VS Code and agent users, the practical signal is that Codex is moving toward longer-running, supervised work where the model can understand local UI context and keep tasks moving across more surfaces.",
    },
    {
      source: "Axios",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["Google", "OpenAI", "Anthropic", "Gemini", "AI agents", "AI infrastructure"],
      title: "Axios: Google Is Trying to Turn Scale Into an AI Advantage",
      url: "https://www.axios.com/2026/05/21/google-ai-anthropic-openai-war",
      summary:
        "Axios framed Google's I/O push as a strategy built around distribution, infrastructure, and product reach rather than only benchmark leadership. The piece contrasts Google with OpenAI and Anthropic, noting that Gemini 3.5 Flash reflects a bet on fast, cheaper models that can be deployed across massive products while the frontier race remains close. For AI-tool watchers, the takeaway is that model selection may increasingly depend on cost, latency, platform reach, and integration depth, not only raw frontier scores.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["Hark", "NVIDIA", "AMD", "Qualcomm", "Salesforce", "AI hardware"],
      title: "Hark Raises $700 Million to Build a Universal AI Interface",
      url: "https://techcrunch.com/2026/05/21/hark-raises-700m-series-a-for-its-secretive-universal-ai-interface/",
      summary:
        "TechCrunch reported that Hark raised a $700 million Series A at a $6 billion post-money valuation to build models, hardware, and a personal AI platform meant to act as a universal interface for digital tasks. The company expects multimodal models this summer and eventual hardware devices, but still has to prove product clarity, privacy handling, and whether a consumer agent can feel useful beyond developer workflows. The story is worth tracking because capital is shifting toward native AI interfaces, not just chat windows and IDE plug-ins.",
    },
    {
      source: "TechCrunch",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["Google", "Gemini", "Gemini Spark", "Android", "AI agents", "Google I/O"],
      title: "TechCrunch Questions Whether Google's Consumer Agent Ecosystem Is Clear Enough",
      url: "https://techcrunch.com/2026/05/21/google-is-pitching-an-ai-agent-ecosystem-to-consumers-who-may-not-buy-it/",
      summary:
        "TechCrunch argued that Google's I/O agent announcements show ambition but also product complexity: information agents, Gemini Spark, Android Halo, Daily Brief, AI-first Search, and agentic Chrome all point toward background assistants, but many features are gated to paid tiers or not broadly available yet. For teams designing AI tools, the useful lesson is product focus: agent capability alone is not enough if users cannot tell which assistant handles which job, what data it sees, and why the workflow is worth trusting.",
    },
    {
      source: "AP News",
      date: "2026-05-18",
      displayDate: "May 18, 2026",
      category: "ai-general-news",
      companies: ["Vatican", "Anthropic", "AI ethics", "AI governance", "Human dignity"],
      title: "AP: Pope Leo XIV and Anthropic Co-Founder to Launch AI Encyclical on May 25",
      url: "https://apnews.com/article/9cf3e07fd691f6af510c4a6f9c8ba353",
      summary:
        "AP reported that Pope Leo XIV and Anthropic co-founder Jack Clark are scheduled to launch the pontiff's first encyclical on May 25, focused on human dignity in the era of artificial intelligence. The item is not a developer-product release, but it is worth tracking because it puts AI governance, labor, safety, and human agency into a major global institutional forum. For teams adopting agents and model-assisted workflows, it reinforces that AI rollouts should be evaluated through trust, accountability, and human-impact lenses, not only through productivity metrics.",
    },
    {
      source: "AP News",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["White House", "AI policy", "OpenAI", "Anthropic", "Google", "Microsoft"],
      title: "White House Calls Off AI Executive Order Signing Over Competitiveness Concerns",
      url: "https://apnews.com/article/trump-ai-executive-order-ee318f35acc8a2c43e47f3ebf26cb459",
      summary:
        "AP reported that President Trump called off a planned May 21 signing ceremony for an AI executive order after concerns that the order could weaken the United States' competitive position in AI. For developer-tool and enterprise AI teams, the practical signal is policy uncertainty: governance, procurement, model testing, and infrastructure rules may keep moving quickly, but not always on a predictable launch schedule.",
    },
    {
      source: "Microsoft",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "EY", "Microsoft 365 Copilot", "Enterprise AI", "AI agents"],
      title: "Microsoft and EY Share Large-Scale Copilot Deployment Metrics",
      url: "https://blogs.microsoft.com/blog/2026/05/21/from-ai-pilots-to-enterprise-impact-why-execution-is-the-new-differentiator/",
      summary:
        "Microsoft said EY is expanding Microsoft 365 Copilot through Microsoft 365 E7 to more than 400,000 people after an initial 150,000-person rollout reported 94% monthly adoption, 85% weekly usage, and a 15% productivity gain. Microsoft also highlighted agentic finance, assurance, and tax workflows, including faster operational lead times and reduced manual document work. The useful takeaway is that credible enterprise AI stories are increasingly judged by measured operating outcomes, not by seat counts alone.",
    },
    {
      source: "GitHub Changelog",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["GitHub", "Microsoft", "GitHub Copilot", "Eclipse", "Open source", "Agent mode"],
      title: "GitHub Open Sources Copilot for Eclipse",
      url: "https://github.blog/changelog/2026-05-21-github-copilot-for-eclipse-is-open-source",
      summary:
        "GitHub open sourced Copilot for Eclipse under the MIT license, exposing the implementation for completions, Next Edit Suggestions, chat, tool calls, agent mode, skills and prompt files, BYOK, custom agents, isolated subagents, the plan agent, and MCP integration. For teams comparing IDE AI tooling, this is a useful transparency milestone because developers can inspect how Copilot workflows are implemented outside VS Code and reason about context handling, agent orchestration, and extension architecture.",
    },
    {
      source: "Visual Studio Code",
      date: "2026-05-21",
      displayDate: "May 21, 2026",
      category: "ai-general-news",
      companies: ["Microsoft", "Visual Studio Code", "GitHub Copilot", "Agents Window", "BYOK", "Remote agents"],
      title: "VS Code 1.122 Iteration Notes Add Remote Agent Tasks and Local Agent Host Defaults",
      url: "https://code.visualstudio.com/updates/v1_122",
      summary:
        "Microsoft updated the VS Code 1.122 iteration notes through May 21 with agent-focused changes: agents can trigger tasks on remote machines, Agents window source-control state refreshes after git operations, /models opens the model picker from chat, BYOK models work in air-gapped scenarios without GitHub authentication, and the local agent host is enabled by default in Insiders builds. Use 1.122 as the freshest official watchlist while 1.121 remains the current stable release reference.",
    },
  ];

  const existingItems = Array.isArray(window.newsFeed) ? window.newsFeed : [];
  window.newsFeed = [...latestUpdates, ...existingItems];
})();
