window.newsFeed = [
  {
    source: "CNBC",
    date: "2026-04-24",
    displayDate: "April 24, 2026",
    category: "new-models",
    companies: ["DeepSeek"],
    title: "DeepSeek Releases V4 Preview — Open-Source, 1M-Token Context, at a Fraction of the Cost",
    url: "https://www.cnbc.com/2026/04/24/deepseek-v4-llm-preview-open-source-ai-competition-china.html",
    summary:
      "Chinese AI startup DeepSeek launched preview versions of its V4 model family, including V4 Pro (1.6T total / 49B active params) and V4 Flash (284B total / 13B active params). V4 is the first open model family built from the ground up around million-token contexts as a default, using a Hybrid Attention Architecture that significantly reduces KV cache usage. The models are open-source and available via the DeepSeek API starting today, priced at $0.14–$1.74 per million input tokens depending on tier.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-23",
    displayDate: "April 23, 2026",
    category: "new-models",
    companies: ["OpenAI"],
    title: "OpenAI Releases GPT-5.5, Its Fastest and Most Capable Model Yet",
    url: "https://techcrunch.com/2026/04/23/openai-chatgpt-gpt-5-5-ai-model-superapp/",
    summary:
      "OpenAI released GPT-5.5, its newest frontier model, just six weeks after GPT-5.4 — a rapid cadence underscoring intense competition among AI labs. GPT-5.5 scores 88.7% on SWE-bench and 92.4% on MMLU, with a 60% reduction in hallucinations versus its predecessor. The model handles multi-step agentic workflows with less user input and is rolling out to Plus, Pro, Business, and Enterprise ChatGPT users, while also powering Codex on NVIDIA infrastructure. API pricing is $5 per million input tokens and $30 per million output tokens.",
  },
  {
    source: "9to5Mac",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["Google", "Apple"],
    title: "Google Confirms Gemini Will Power a Revamped, More Conversational Siri in 2026",
    url: "https://9to5mac.com/2026/04/22/google-teases-gemini-powered-siri-upgrade-during-cloud-next-keynote/",
    summary:
      "Google Cloud CEO Thomas Kurian confirmed at Cloud Next that Apple has selected Gemini as the foundation for the next generation of Apple Intelligence and Siri. Under a multi-year deal, Apple Foundation Models will be built on Gemini technology with Google Cloud handling training and inference. Phase 1 has already begun with iOS 26.4 bringing better context awareness to Siri; Phase 2 targets iOS 27 this September with full back-and-forth conversational Siri supporting 20+ exchanges and complex tasks.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["Google"],
    title: "Google Launches Gemini Enterprise Agent Platform at Cloud Next",
    url: "https://techcrunch.com/2026/04/22/google-makes-an-interesting-choice-with-its-new-agent-building-tool-for-enterprises/",
    summary:
      "At Google Cloud Next, CEO Sundar Pichai announced the Gemini Enterprise Agent Platform, Google's answer to Amazon Bedrock AgentCore and Microsoft Foundry. The tool is aimed at IT and technical teams building and managing agents at scale, and supports Google's own Gemini models alongside Anthropic's Claude Opus, Sonnet, and Haiku. A separate Gemini Enterprise app handles business-user workflows like scheduling and file management.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["Google"],
    title: "Google Cloud Launches TPU 8t and 8i — Two Specialized AI Chips to Compete with Nvidia",
    url: "https://techcrunch.com/2026/04/22/google-cloud-next-new-tpu-ai-chips-compete-with-nvidia/",
    summary:
      "Google announced its eighth-generation TPU family at Cloud Next, splitting the chip into two purpose-built designs: the TPU 8t for model training and the TPU 8i for inference. Google claims up to 3x faster training, 80% better performance per dollar versus prior generations, and the ability to cluster 1 million-plus TPUs together. The chips supplement rather than replace Nvidia hardware in Google Cloud's fleet.",
  },
  {
    source: "VentureBeat",
    date: "2026-04-22",
    displayDate: "April 22, 2026",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "OpenAI Unveils Workspace Agents as Successor to Custom GPTs for Enterprises",
    url: "https://venturebeat.com/orchestration/openai-unveils-workspace-agents-a-successor-to-custom-gpts-for-enterprises-that-can-plug-directly-into-slack-salesforce-and-more",
    summary:
      "OpenAI announced Workspace Agents, replacing Custom GPTs as its primary enterprise agent product. Agents can be created and accessed from ChatGPT and embedded directly into Slack, Salesforce, and other third-party platforms. Users can communicate with agents across disparate channels and grant them access to data from connected apps, positioning them as persistent workflow participants rather than standalone chatbot sessions.",
  },
  {
    source: "VentureBeat",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "ai-general-news",
    companies: ["Google"],
    title: "Google Launches Deep Research and Deep Research Max with MCP Support and Private Data Access",
    url: "https://venturebeat.com/technology/googles-new-deep-research-and-deep-research-max-agents-can-search-the-web-and-your-private-data",
    summary:
      "Google unveiled two new API-accessible research agents built on Gemini 3.1 Pro. Deep Research is optimized for speed in interactive apps; Deep Research Max uses extended test-time compute for exhaustive background research, scoring 93.3% on DeepSearchQA. Both agents add Model Context Protocol support, letting them query private databases and third-party enterprise data sources alongside the open web, plus native chart and infographic generation inside reports.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "mythos-news",
    companies: ["Anthropic"],
    title: "Unauthorized Group Gained Access to Anthropic's Exclusive Cyber Tool Mythos Through Third-Party Contractor",
    url: "https://techcrunch.com/2026/04/21/unauthorized-group-has-gained-access-to-anthropics-exclusive-cyber-tool-mythos-report-claims/",
    summary:
      "Bloomberg reported that members of a private Discord channel—interested in unreleased AI models—gained access to Mythos on the same day it was publicly announced, exploiting credentials held by a third-party contractor working for Anthropic. The group guessed the model's online location based on Anthropic's known URL patterns, provided screenshots and a live demo to Bloomberg, and has been using the model regularly since. Anthropic confirmed it is investigating but said it has found no evidence of impact to its own systems.",
  },
  {
    source: "TechCrunch",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "ai-general-news",
    companies: ["SpaceX", "xAI"],
    title: "SpaceX Partners with Cursor and Holds Option to Acquire the Coding AI Startup for $60B",
    url: "https://techcrunch.com/2026/04/21/spacex-is-working-with-cursor-and-has-an-option-to-buy-the-startup-for-60-billion/",
    summary:
      "SpaceX announced a partnership with Cursor to co-develop a 'next-generation coding and knowledge work AI,' pairing Cursor's developer distribution with SpaceX's Colossus supercomputer. The deal includes an option to acquire Cursor for $60 billion later this year, up from a $50 billion valuation Cursor was eyeing in an imminent funding round. The move comes as SpaceX preps for its IPO and as Cursor and xAI chip resources grow closer—two senior Cursor engineering leads departed to join xAI earlier this month.",
  },
  {
    source: "Ars Technica",
    date: "2026-04-21",
    displayDate: "April 21, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "Mozilla"],
    title: "Mozilla: Mythos Found 271 Security Vulnerabilities in Firefox 150",
    url: "https://arstechnica.com/ai/2026/04/mozilla-anthropics-mythos-found-271-zero-day-vulnerabilities-in-firefox-150/",
    summary:
      "Mozilla reported that early access to Anthropic's Mythos Preview allowed its security team to identify 271 previously unknown security vulnerabilities in the Firefox 150 codebase before release. According to Mozilla's CTO, the model's findings were comparable to elite human security research, but delivered much faster.",
  },
  {
    source: "Anthropic",
    date: "2026-04-16",
    displayDate: "April 16, 2026",
    category: "new-models",
    companies: ["Anthropic"],
    title: "Introducing Claude Opus 4.7",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    summary:
      "Anthropic positioned Claude Opus 4.7 as a direct upgrade for advanced software engineering and long-running agentic work, with stronger instruction following, better multimodal handling, and new deployment safeguards informed by its Mythos-class safety work.",
  },
  {
    source: "Level Up Coding",
    date: "2026-04-12",
    displayDate: "April 12, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "Google", "Microsoft", "AWS", "Apple"],
    title: "Mythos Used by Major Tech Firms Found Bugs Across Every Major OS",
    url: "https://levelup.gitconnected.com/anthropics-new-ai-found-bugs-in-every-major-os-and-browser-and-they-re-not-releasing-it-6cae9ca4fa47",
    summary:
      "According to Level Up Coding, companies such as Apple, Google, Microsoft, and AWS ran Mythos through Project Glasswing to analyze operating systems and browser code. The model identified high-severity vulnerabilities across all major platforms, including cases where automated tools and human reviewers had failed for years.",
  },
  {
    source: "VentureBeat",
    date: "2026-04-10",
    displayDate: "April 10, 2026",
    category: "mythos-news",
    companies: ["Anthropic", "Microsoft", "AWS", "Apple", "Cisco"],
    title: "Enterprise Partners Ran Mythos Against Critical Infrastructure",
    url: "https://venturebeat.com/security/mythos-detection-ceiling-security-teams-new-playbook",
    summary:
      "VentureBeat reported that companies participating in Anthropic's Project Glasswing, including Cisco, Microsoft, AWS, Apple, Palo Alto Networks, and the Linux Foundation, had been running Mythos against their own infrastructure and key open-source dependencies. These tests revealed long-standing vulnerabilities, including bugs that had survived decades of human review.",
  },
  {
    source: "Forbes",
    date: "2026-04-08",
    displayDate: "April 8, 2026",
    category: "mythos-news",
    companies: ["Anthropic"],
    title: "Fortune 500 and Open-Source Maintainers Found Critical Zero-Days",
    url: "https://www.forbes.com/sites/jonmarkman/2026/04/08/what-is-claude-mythos-and-why-anthropic-wont-let-anyone-use-it/",
    summary:
      "Forbes detailed how organizations with access to Mythos discovered thousands of zero-day vulnerabilities across major operating systems, browsers, and widely used libraries. In multiple cases, Mythos was also able to produce working exploits after initial discovery, increasing concern about how easily the findings could be weaponized.",
  },
  {
    source: "GitHub Blog",
    date: "2026-03-19",
    displayDate: "March 19, 2026",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "How Squad Runs Coordinated AI Agents Inside Your Repository",
    url: "https://github.blog/ai-and-ml/github-copilot/how-squad-runs-coordinated-ai-agents-inside-your-repository/",
    summary:
      "GitHub described Squad as a repository-native multi-agent workflow that uses shared project memory, specialist agents, and explicit reviewer separation to keep orchestration inspectable instead of hiding everything inside one chat loop.",
  },
  {
    source: "OpenAI",
    date: "2025-04-14",
    displayDate: "April 14, 2025",
    category: "new-models",
    companies: ["OpenAI"],
    title: "Introducing GPT-4.1 in the API",
    url: "https://openai.com/index/gpt-4-1/",
    summary:
      "OpenAI introduced GPT-4.1, GPT-4.1 mini, and GPT-4.1 nano with major gains in coding, instruction following, and long-context handling, positioning the family as lower-cost, more reliable infrastructure for agentic applications.",
  },
  {
    source: "OpenAI",
    date: "2025-03-11",
    displayDate: "March 11, 2025",
    category: "ai-general-news",
    companies: ["OpenAI"],
    title: "New Tools for Building Agents",
    url: "https://openai.com/index/new-tools-for-building-agents/",
    summary:
      "OpenAI announced the Responses API, built-in web search, file search, computer use, and an Agents SDK, framing them as the first coordinated building blocks for production agent development and future migration away from the Assistants API.",
  },
  {
    source: "Anthropic",
    date: "2025-02-24",
    displayDate: "February 24, 2025",
    category: "new-models",
    companies: ["Anthropic"],
    title: "Claude 3.7 Sonnet and Claude Code",
    url: "https://www.anthropic.com/news/claude-3-7-sonnet",
    summary:
      "Anthropic launched Claude 3.7 Sonnet as a hybrid reasoning model and paired it with Claude Code, a research-preview coding tool designed to search code, edit files, run tests, and collaborate directly from the terminal.",
  },
  {
    source: "GitHub Blog",
    date: "2024-05-21",
    displayDate: "May 21, 2024",
    category: "ai-general-news",
    companies: ["GitHub", "Microsoft"],
    title: "Introducing GitHub Copilot Extensions",
    url: "https://github.blog/news-insights/product-news/introducing-github-copilot-extensions/",
    summary:
      "GitHub introduced Copilot Extensions to pull partner tools and internal services into Copilot Chat, aiming to reduce context switching by letting developers query, act, and deploy across their stack from natural-language workflows in GitHub and VS Code.",
  },
];